from . import res_partner_inherit
from . import borrow_laptop_line
from . import borrow_laptop
from . import kelas
from . import product_inherit
from . import return_laptop
from . import stock_lot_inherit
from . import jurusan
from . import tingkat